### ISSUE TITLE
F-2: Administrative collections

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#18]
From the SOW:

> Implement DLXS-like collection groupings where an item can only be contained by a single administrative collection.  Provide ability to create and manage administrative collections, including ability to manage collection membership.  Administrative collections will be required to implement DLXS-like collection level customizations.

Gather requirements for Admin collections.

Questions:
- [x] Where do self-deposits go?  Can the user choose which admin collection their work will be in?  Or is there a limited set of choices?  Or a single self-deposit collection?
- [x] What does it mean to implement DLXS-like collection customizations?

**Comment by acozine** [comment]
Instead of true self-deposit, this system will have admin-only single-item ingest. So the person who ingests the object does decide which admin collection it belongs to.

**Comment by jcoyne** [comment]
- [x] All objects belong to exactly one AdminCollection #170
- [x] Admins should have CRUD for admin collections #164, #165, #166
- [x] Objects should have admin collection selector on the edit page #170
- [x] On the show page, objects should display their admin collection
- [x] Facet on admin collection (F-3) #171
- [x] ~~A show page for the admin collection that offers a search portal to all the items.~~ _I think this is redundant if you have an admin collection facet - MHB_
- [x] There is a Admin Collections index page and a way to navigate to it - _as a first pass, just use the collection facet - #171_
- [x] Update the importer so that it adds imported records to the correct Admin Collection #167, #168, #169

**Comment by acozine** [comment]
- [x] create a wireframe to show WUSTL at 9/2 demo

**Comment by mark-dce** [comment]
Wireframes are included in individual stories.

This story is complete when individual stories listed against acceptance criteria above are complete.
