### ISSUE TITLE
A-8: AuthN & AuthZ

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#19]
From the SOW:

> Integrate the repository with WU’s authentication and authorization infrastructure.  The core access policies supported by Worthwhile are: public access, restricted institutional access (via login), and private to the depositor and administrators (via login).  This functionality is largely an outcome of the base application development and is listed here as a checkpoint to measure integration with the WU authentication infrastructure.

Questions:
- [ ] What is the authentication infrastructure? (NTLM or Kerberos)
- [x] What is the authorization technology?
- [x] Can we get URLs & credentials if needed?
- [x] Are you able to manage groups/roles with your campus authorization?  Or do we need the app to manage groups locally?

**Comment by acozine** [comment]
They are using ActiveDirectory - they have campuswide system and a system controlled by the library. Groups will come from the library ActiveDirectory system.

**Comment by acozine** [comment]
1. Authentication (checking the password for user 'msellan' on login)
   will come from the campus-wide ActiveDirectory server
2. Authorization (checking that 'msellan' is a member of the admin group,
   therefore he can upload new objects) will come from the library
   ActiveDirectory server

Mark S. says:
There¹s a one way trust relationship between the library domain (WULIB) and the machines domain (ACCOUNTS) where we trust them.  So I think you¹ll just need bind credentials for the library domain.

Admin user and password for the wulib ActiveDirectory server are on the ec2 server in shared/config/activedir.yml - I'll fill in the hostname, port, organizational units, and SSL details (if any) when I get them.

**Comment by mark-dce** [comment]
For # 1 in Alicia's comment above, we should ask Mark S. if the campus-wide ActiveDriectory is exposed via LDAP - this would be the most common pattern that I know of in the Hydra community for handling this.

For # 2 - it sounds like we should tell WU that the first release of goldenseal will assign administrative rights via the role-mapper file here: https://github.com/curationexperts/goldenseal/blob/master/config/role_map.yml

**Comment by val99erie** [comment]
I emailed the wustl team to confirm that we can use LDAP.  Waiting for reply

**Comment by acozine** [comment]
ldapsearch utility works - they need to change the setup of the admin group, but ldap protocol should be fine for connecting to ActiveDirectory - I'm removing the Blocked label

**Comment by acozine** [comment]
Blocked by #129. WUSTL admins are unable to create a group in their ActiveDirectory server with objectClass: groupofUniqueNames.

**Comment by acozine** [comment]
Changed the admin group on our ldap server from a groupofUniqueNames with uniqueMembers to a groupofNames with members. Succeeds on our server; I've asked Mark Sellan to deploy and test.

**Comment by acozine** [comment]
Succeeded in connecting to the WULIB ActiveDirectory server. Authz and authn work correctly - members of the 'admin' group can log in, see private objects, and edit objects. Logins without 'admin' group membership can log in, see Campus-only objects, but not edit. We tried connecting to the main campus AD server, and ran into some issues which Mark Sellan will take to the Central IT for resolution.

**Comment by acozine** [comment]
Bare-bones documentation here: https://github.com/curationexperts/goldenseal/wiki/LDAP-ActiveDirectory-notes
