### ISSUE TITLE
A-6: Core digital object models

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#45]
From the SOW:

> DCE will implement the core object types supported by Worthwhile: PDFs; Microsoft Office, OpenOffice, & LibreOffice Documents; Tiff & JPEG Images; MP3 & Wave Audio; and open source Video formats. This functionality is largely an outcome of the base application development and is listed here as a checkpoint to measure project progress.
- [x] Can ingest and download a Word Document
- [x] Can ingest and download an Excel Spreadsheet
- [x] Can ingest and download a PowerPoint Presentation
- [x] Can ingest and display a PDF
- [x] Can ingest and display an Image (TIFF)
- [x] Can ingest and display an Image (JPEG)
- [x] Can ingest and display an Image (JP2)
- [x] Can ingest and play MP3 audio
- [x] Can ingest and play WAV audio
- [x] Can ingest and play MPEG-1 video 
- [x] Can ingest and play MPEG-2 video 
- [x] Can ingest and play MPEG-4 video 
- [x] Can ingest and play WEBM video
- [x] Can ingest and play AVI video
- [x] Can ingest and play MOV video

**Comment by jcoyne** [comment]
@mark-dce By "formats" do you mean container formats or audio/video codecs?

**Comment by mark-dce** [comment]
@jcoyne primarily container formats - since we're using ffmpeg, we can just point WU at the list of supported codecs in the ffmpeg docs.

**Comment by jcoyne** [comment]
Okay, then lets say Advanced Systems Format, AVI, MPEG, MP4, Matroska, QuickTime and WebM as the supported containers

**Comment by mark-dce** [comment]
I can round-trip all of the listed file types - upload when creating a new work and download from the work later.  I've opened separate tickets for the video and audio playback issues with the player on the show pages for each.
