### ISSUE TITLE
B-1 Gather sample content 

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#48]
From SOW:

> DCE and WU will collaborate to identify sample content and metadata for the initial collection to be migrated.   In addition, we will identify up to 3 additional content types or collections for migration analysis, especially high-risk or high-complexity collections such as the Red Brush collection.  This story does not have specific time allocated to it, but is listed as a placeholder to ensure these activities take place early on in the development timeline.
- [x] Identify the primary collection for testing
- [x] Representative samples from primary collection
- [x] Media and associated transcript samples
- [x] Image samples
- [x] TEI samples

**Comment by mark-dce** [comment]
We need to identify and other missing samples required to complete Deliverables A-E and communicate our needs to the WU team ASAP.

**Comment by mark-dce** [comment]
Primary collection: Fanny Lewald - TEI + page images - need 2-3 additional 
Video collection: America's war on Poverty 
Alternate video collection: Great Depression

**Comment by acozine** [comment]
We've received sample metadata and content for the America's War on Poverty collection. On wustl.curationexperts.com, /opt/sample-data/Americas_War_on_Poverty_TEI_transcripts/ contains two TEI files, and /opt/sample-data/Addonizio-Avila-Interviews/ contains two video .MOV files and a .txt metadata file.

**Comment by mark-dce** [comment]
Samples are on sandbox server and box directory.

From Andrew:

> The .mp4 video files that correspond to the TEI XML transcriptions are available in the Box folder.
> The TEI XML files here: /Box Sync/Hydra/DCE_WU_content_model/Americas_War_on_Poverty_TEI_transcripts/
> The video files here: /Box Sync/Hydra/DCE_WU_content_model/Addonizio-Avila-Interviews/
> The above files are part of the America’s War on Poverty collection
> This is the collection that will be used to demonstrate DELIVERABLE J: Synchronized transcript support (NOT the Great Depression—apologies for confusion.) 
> (For WU personnel: we will also be using the same collection--America’s War on Poverty—as the collection for the WU implementation of Avalon.)
> It may or may not be a complete collection by the end of the phase 1 development cycle
> The main collection to be ingested for the phase 1 development cycle will be Fanny LeWald:
> A sample TEI XML files and associated image files here: /Box Sync/Hydra/DCE_WU_content_model/fanny-lewald-TEI-textimage/
