### ISSUE TITLE
C-1	Create Digital object model for WU Image assets

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#53]
From the SOW:

> Implement the customizations necessary to associate images into multi-image works including multi-sided and accordion type images.  (Note that book-like objects with associated transcripts are covered under E-1)
- [x] Metadata can be associated an image-class work
- [x] One or more images can be attached to an image-class work
- [x] Images attached to a work can be ordered (eg. 2-sided and accordion images)

**NOTE:**
This story covers the model only, UI features are covered in #11 (upload), #31 (show), & #27 (search)
