### ISSUE TITLE
D-1	Create Digital object model for WU Time based media

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#55]
From the SOW:

> Implement the customizations necessary support audio and video based works with optional associated transcript objects.
- [x] Media works can have basic metadata attached
- [x] Media works can have one or more files attached
- [x] Media works can have a primary media file identified - select representative example in editor
- [ ] Media works can have an optional transcript file associated with the media - see #62
- [x] Media works can have an arbitrary number of optional other files attached
