### ISSUE TITLE
E-1	Create Digital object model for WU Text (TEI) assets

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#56]
From the SOW:

> Implement the customizations necessary to support archival TEI objects and any delivery proxies (page images, PDF renderings) associated with the text item.  
- [x] Text (TEI) works can have metadata associated with them
- [x] Text works can have one or more files attached
- [x] Text works can have a primary TEI file specified
- [x] Text works have a model for associating page images with the primary text transcript
